on:
  pull_request:
    branches: [ "test" ]
    types: [opened, reopened, synchronize]

jobs:
  testing:
    name: Run test
    runs-on: ubuntu-latest

    steps:
      - name: Get PR labels
        id: pr-labels
        uses: joerick/pr-labels-action@v1.0.6
        run: |
          echo "$GITHUB_PR_LABEL_RELEASE_PATCH"
          echo "$GITHUB_PR_LABEL_RELEASE_MINOR"
          echo "$GITHUB_PR_LABEL_RELEASE_MAJOR"