on:
  pull_request:
    branches: [ "test" ]
    types: [opened, reopened, synchronize]

jobs:
  testing:
    name: Run test
    runs-on: ubuntu-latest

    steps:
      - name: Get pull request labels
        run: |
          labels=${{ github.event.pull_request.labels.*.name }}
          for ((i=0; i<${labels[@]}; i++)); do echo "${labels[$i]}"; done