on:
  pull_request:
    branches: [ "test" ]
    types: [opened, reopened, synchronize]

jobs:
  testing:
    name: Run test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get previous tag
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: v0.0.0

      - name: Get PR labels
        id: pr-labels
        uses: joerick/pr-labels-action@v1.0.6

      - name: Print release labels
        run: |
          previous_tag${{ steps.previoustag.outputs.tag }}
          version_parts=(${${previous_tag:1}//./ })
          
          major_part=${version_parts[0]}
          minor_part=${version_parts[1]}
          patch_part=${version_parts[2]}
          
          if [ -n "${GITHUB_PR_LABEL_RELEASE_MAJOR}" ]; then
            echo "Major update"
            major_part=$((major_part+1))
          elif [ -n "$GITHUB_PR_LABEL_RELEASE_MINOR" ]; then
            echo "Minor update"
            minor_part=v$((minor_part+1))
          else
            echo "Patch update"
            patch_part=v$((patch_part+1))
          
          new_version="v${major_part}.${minor_part}.${patch_part}"
          echo "New version: ${new_version}"