on:
  pull_request:
    branches: [ "test" ]
    types: [opened, reopened, synchronize]

jobs:
  testing:
    name: Run test
    runs-on: ubuntu-latest

    steps:
      - name: Get pull request labels
        run: |
          for ((i=0; i < ${${{ github.event.pull_request.labels.*.name }}}; i++ )); do echo "${my_array[$i]}"; done